CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS unaccent;

CREATE COLLATION IF NOT EXISTS "pt-BR-x-icu" (
    provider = icu,
    locale = 'pt-BR'
);

CREATE SCHEMA IF NOT EXISTS cliente;
CREATE SCHEMA IF NOT EXISTS gerente;
CREATE SCHEMA IF NOT EXISTS conta_command;
CREATE SCHEMA IF NOT EXISTS conta_query;
