server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: cliente
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      write-dates-as-timestamps: false
      write-bigdecimal-as-plain: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:bantads}?currentSchema=cliente
    username: ${POSTGRES_USER:bantads_cliente}
    password: ${POSTGRES_PASSWORD:change-me}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: cliente
        jdbc:
          time_zone: America/Sao_Paulo
  flyway:
    enabled: true
    schemas: cliente
    default-schema: cliente
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:bantads}
    password: ${RABBIT_PASSWORD:change-me}
