export const CommandTypes = {
  APROVAR_CLIENTE: 'aprovar-cliente',
  INSERIR_GERENTE: 'inserir-gerente',
  REMOVER_GERENTE: 'remover-gerente',
  RELATORIO_CLIENTES: 'relatorio-clientes',
  CLIENTE_MARCAR_APROVADA: 'cliente.marcar-aprovada',
  CLIENTE_DESMARCAR_APROVADA: 'cliente.desmarcar-aprovada',
  CLIENTE_MARCAR_NAO_APROVADA: 'cliente.marcar-nao-aprovada',
  CLIENTE_CRIAR: 'cliente.criar',
  CLIENTE_REMOVER: 'cliente.remover',
  CLIENTE_OBTER_POR_CPFS: 'cliente.obter-por-cpfs',
  GERENTE_INSERIR: 'gerente.inserir',
  GERENTE_REMOVER: 'gerente.remover',
  GERENTE_INATIVAR: 'gerente.inativar',
  GERENTE_REATIVAR: 'gerente.reativar',
  GERENTE_LISTAR_ATIVOS: 'gerente.listar-ativos',
  CONTA_ESCOLHER_GERENTE_MENOS_CLIENTES: 'conta.escolher-gerente-menos-clientes',
  CONTA_CRIAR: 'conta.criar',
  CONTA_REMOVER: 'conta.remover',
  CONTA_IDENTIFICAR_CONTA_PARA_NOVO_GERENTE: 'conta.identificar-conta-para-novo-gerente',
  CONTA_ATRIBUIR_GERENTE: 'conta.atribuir-gerente',
  CONTA_REATRIBUIR_GERENTE: 'conta.reatribuir-gerente',
  CONTA_TRANSFERIR_CONTAS_DO_GERENTE: 'conta.transferir-contas-do-gerente',
  CONTA_REVERTER_TRANSFERENCIA_GERENTES: 'conta.reverter-transferencia-gerentes',
  AUTH_CRIAR_CLIENTE: 'auth.criar-cliente',
  AUTH_CRIAR_GERENTE: 'auth.criar-gerente',
  AUTH_REMOVER: 'auth.remover',
  AUTH_DESATIVAR: 'auth.desativar',
  AUTH_REATIVAR: 'auth.reativar',
  EMAIL_SENHA_CLIENTE: 'email.senha-cliente',
  EMAIL_FALHA_APROVACAO: 'email.falha-aprovacao',
  EMAIL_REJEICAO: 'email.rejeicao',
  EMAIL_TROCA_GERENTE: 'email.troca-gerente',
  SAGA_INVALIDAR_SESSAO: 'saga.invalidar-sessao',
} as const;

export type CommandType = (typeof CommandTypes)[keyof typeof CommandTypes];
